### PR TITLE
fix(project): added parsing of minInput to allow it to be passed as literal tag attribute

### PR DESCRIPTION
**Pull request by Mobe91**
Fix for #43

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Maybe:

```js
let minInput = this.minInput;

if (typeof minInput === 'string') {
  minInput = Number.parseInt(minInput);
}

return ((this.value && this.value.length) || 0) >= minInput;
```

And then also 2 spaces instead of 4.

Other than that, nice PR 👍

**Comment by Mobe91** [comment]
Hmm are modern javascript engines intelligent enough to prevent the redundant write in case the if condition evaluates to true?

**Comment by RWOverdijk** [comment]
This PR isn't needed anymore, right?

**Comment by Mobe91** [comment]
No, closing it.

**Pull request closed without merging**
