### PR TITLE
Add support for search on multiple fields

### PR DESCRIPTION
**Pull request by jeremyvergnas**
Add support for search on multiple fields

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@jeremyvergnas Maybe add an if for the or/and distinction? Now it's _always_ an or, which isn't BC.

**Comment by jeremyvergnas** [comment]
@RWOverdijk The `and` was only applied when `criteria` was provided before, I didn't change that.
Now it is gonna be something like this if criteria is provided:
```
attribute = ['name', 'country'];
criteria = {city: 'Amsterdam'};

Model.find({
	or: [{
		name: {contains: 'Rot'}
	}, {
		country: {contains: 'Rot'}
	}], 
	city: 'Amsterdam'}
)
```

Though, I can add a bindable (`useAnd` for instance) so we can specify whether it should be an `or` or an `and` when searching on the multiple given attributes.

**Comment by jeremyvergnas** [comment]
@RWOverdijk ignore my previous comment :)

Feedback processed.

**Comment by RWOverdijk** [comment]
👍

**Pull request merged**
